config/routes.rb
SampleApp::Application.routes.draw do
  resources :schedules
  resources :pets
  resources :appointments
  resources :users
  match '/admin',     to: 'users#index',        via: 'get'
  match '/reception', to: 'appointments#index', via: 'get'
  match '/doctor',    to: 'pets#index',         via: 'get'
  match '/customer',  to: 'schedules#index',    via: 'get'
  match '/help',      to: 'welcome#help',       via: 'get'

   root 'welcome#home'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  validates :customer, :pet, :reason, presence: true
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  validates :name, :breed, presence: true, length:{maximum:35 }
  validates :age, :weight, :dated, presence: true
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
validates :name, :reason, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, length: {maximum: 35}
  validates :zip_code, length:{maximum:5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def new
    @appointment = Appointment.new
  end
  def show
    @appointment = Appointment.find(params[:id])
  end
  def index
    @appointments = Appointment.all
  end
  def edit
    @appointment = Appointment.find(params[:id])
  end
  def update
    @appointment = Appointment.find(params[:id])
    if @appointment.update(params[:appointment].permit(:customer, :pet, :reason, :dated, :doctor))
      redirect_to @appointment
    else
      render 'edit'
    end
  end
  def create
    @appointment = Appointment.new(params[:appointment].permit(:customer, :pet, :reason, :dated, :doctor))
    if @appointment.save
      redirect_to @appointment
    else
      render 'new'
    end
  end
  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy
    redirect_to appointments_path
  end
  private
  def appointment_params
    params.require(:appointment).permit(:customer, :pet, :reason, :dated, :doctor)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def new
    @pet = Pet.new
  end
  def show
    @pet = Pet.find(params[:id])
  end
  def index
    @pets = Pet.all
  end
  def edit
    @pet = Pet.find(params[:id])
  end
  def update
    @pet = Pet.find(params[:id])
    if @pet.update(params[:pet].permit(:name, :pet_type, :breed, :age, :weight, :dated))
      redirect_to @pet
    else
      render 'edit'
    end
  end
  def create
    @pet = Pet.new(params[:pet].permit(:name, :pet_type, :breed, :age, :weight, :dated))
    if @pet.save
      redirect_to @pet
    else
      render 'new'
    end
  end
  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path
  end
  private
  def pet_params
    params.require(:pet).permit(:name, :pet_type, :breed, :age, :weight, :dated)
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def new
    @schedule = Schedule.new
  end
  def index
    @schedules = Schedule.all
  end
  def show
    @schedule = Schedule.find(params[:id])
  end
  def edit
    @schedule = Schedule.find(params[:id])
  end
  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params[:schedule].permit(:name, :reason, :dated))
      redirect_to @schedule
    else
      render 'edit'
    end
  end
  def create
    @schedule = Schedule.new(params[:schedule].permit(:name, :dated, :reason))
    if @schedule.save
      redirect_to @schedule
    else
      render 'new'
    end
  end
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    redirect_to schedules_path
  end
  private
  def pet_params
    params.require(:schedule).permit(:name,:dated, :reason)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def show
    @user = User.find(params[:id])
  end
  def index
    @users = User.all
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])

    if @user.update(params[:user].permit(:name, :address, :city, :state, :zip_code, :school, :years_practice))
      redirect_to @user
    else
      render 'edit'
    end
  end
  def create
    @user = User.new(params[:user].permit(:name, :address, :city, :state,:zip_code, :school, :years_practice))
    if @user.save
    redirect_to @user
    else
      render 'new'
   end
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end
  private
  def user_params
    params.require(:user).permit(:name, :address, :city, :state,:zip_code, :school, :years_practice)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Veterinary Practice Sample App "
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/appointments/_form.html.erb
<%= form_for @appointment do |f| %>
    <% if @appointment.errors.any? %>
        <div id="errorExplanation">
          <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited
            this appointment from being saveed:</h2>
          <ul>
            <% @appointment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :Customer %>
      <%= f.text_field :customer %>
    </p>
    <p>
      <%= f.label :Pet %>
      <%= f.text_field :pet %>
    </p>
    <p>
      <%= f.label :Reason %>
      <%= f.text_field :reason %>
    </p>

    <p>
      <%= f.label :Appointment_Date %>
      <%= f.date_select :dated %>
    </p>
    <p>
      <%= f.label :Doctor %>
      <% options= ['Bob', 'Susan'] %>

      <%= f.select :doctor, options, {}, :disabled => false %>

    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>
<%= render 'form' %>
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<% provide(:title, 'Listing Appointments') %>
<h1>Listing Appointments</h1>
<table>
  <tr>
    <th>Customer</th>
    <th>Pet</th>
    <th>Reason</th>
    <th>Appointment Date</th>
    <th>Doctor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.customer %></td>
        <td><%= appointment.pet %></td>
        <td><%= appointment.reason %></td>
        <td><%= appointment.dated %></td>
        <td><%= appointment.doctor %> </td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment_path(appointment),
                        method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
  <% end %>
</table>
<br/>
<%= link_to 'New appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>
<%= render 'form' %>
<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p>
  <strong>Customer:</strong>
  <%= @appointment.customer %>
</p>
<p>
  <strong>Pet:</strong>
  <%= @appointment.pet %>
</p>
<p>
  <strong>Reason:</strong>
  <%= @appointment.reason %>
</p>
<p>
  <strong>Date:</strong>
  <%= @appointment.dated %>
</p>
<p>
  <strong>Doctor:</strong>
  <%= @appointment.doctor %>
</p>
<%= link_to 'Back', appointments_path %>
| <%= link_to 'Edit', edit_appointment_path(@appointment) %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Sign in as <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Admin", admin_path %></li>
              <li><%= link_to "Receptionist", reception_path %></li>
              <li><%= link_to "Doctor", doctor_path %></li>
              <li><%= link_to "Customer", customer_path %></li>
            </ul>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
 <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/pets/_form.html.erb
<%= form_for @pet do |f| %>
    <% if @pet.errors.any? %>
        <div id="errorExplanation">
          <h2><%= pluralize(@pet.errors.count, "error") %> prohibited
            this pet from being saved:</h2>
          <ul>
            <% @pet.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :Name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :Pet_Type %>
      <% options= ['Cat', 'Dog', 'Bird'] %>
      <%= f.select :pet_type, options, {}, :disabled => false %>
    </p>
    <p>
      <%= f.label :Breed %><br>
      <%= f.text_field :breed%>
    </p>
    <p>
      <%= f.label :Age %>
      <%= f.text_field :age %>
    </p>
    <p>
      <%= f.label :Weight %>
      <%= f.text_field :weight %>
    </p>
    <p>
      <%= f.label :Date %>
      <%= f.date_select :dated %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>
<%= render 'form' %>
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<%= provide(:title, 'Listing Pets') %>
<h1>Listing Pets</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Breed</th>
    <th>Age</th>
    <th>Weight</th>
    <th>Date of last visit</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td> <%= pet.pet_type %></td>
        <td><%= pet.breed %></td>
        <td><%= pet.age %></td>
        <td><%= pet.weight %></td>
        <td><%= pet.dated %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet_path(pet),
                        method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
  <% end %>
</table>
<%= link_to 'New pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>
<%= render 'form' %>
<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>
<p>
  <strong>Type:</strong>
  <%= @pet.pet_type %>
</p>
<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>
<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>
<p>
  <strong>Date:</strong>
  <%= @pet.dated %>
</p>
<%= link_to 'Back', pets_path %>
| <%= link_to 'Edit', edit_pet_path(@pet) %>

app/views/schedules/_form.html.erb
<%= form_for @schedule do |f| %>
    <% if @schedule.errors.any? %>
        <div id="errorExplanation">
          <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited
            this schedule from being saved:</h2>
          <ul>
            <% @schedule.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :Pet_Name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :Date %>
      <%= f.date_select :dated %>
    </p>
    <p>
      <%= f.label :Reason %>
      <%= f.text_area :reason %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>
<%= render 'form' %>
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<% provide(:title, 'Listing Schedules') %>
<h1>Listing Schedules</h1>
<table>
  <tr>
    <th>Pet Name</th>
    <th>Reason</th>
    <th>Date of next appointment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.name %></td>
        <td><%=schedule.reason %></td>
        <td><%= schedule.dated %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule_path(schedule),
                        method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
  <% end %>
</table>
 <%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>
<%= render 'form' %>
<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<h1>Schedule</h1>
<p>
<strong>Name:</strong>
  <%= @schedule.name %>
</p>
<p>
  <strong>Date:</strong>
  <%= @schedule.dated %>
</p>
<p>
  <strong>Reason:</strong>
  <%= @schedule.reason %>
</p>
<%= link_to 'Back', schedules_path %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div id="errorExplanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited
            this user from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :Name %>
      <%= f.text_field :name, :placeholder => "full name" %>
    </p>

    <p>
      <%= f.label :Address %>
      <%= f.text_area :address %>
    </p>
    <p>
      <%= f.label :City %>
      <%= f.text_field :city %>
    </p>
    <p>
      <%= f.label :State %>
      <%= f.text_field :state %>
    </p>
    <p>
      <%= f.label :Zip_code %>
      <%= f.text_field :zip_code, :placeholder => "eg. 12345"%>
    </p>
    <p>
      <%= f.label :School %>
      <%= f.text_field :school %>
    </p>
    <p>
      <%= f.label :Years_practice %>
      <%= f.text_field :years_practice, :placeholder => "1..100" %>
    </p>


    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<%= render 'form' %>
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% provide(:title, 'Listing Users')  %>
<h1>Listing Users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address </th>
    <th>City</th>
    <th>State</th>
    <th>Zip code</th>
    <th>School</th>
    <th>Years of Practice</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.address %></td>
        <td><%= user.city %></td>
        <td><%= user.state %></td>
        <td><%= user.zip_code %></td>
        <td><%= user.school %></td>
        <td><%= user.years_practice %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user_path(user),
                        method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>
<br/>
<%= link_to 'New user', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>
<%=render 'form' %>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>User Detail</h1>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>
<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>
<p>
  <strong>State:</strong>
  <%= @user.state %>
</p>
<p>
  <strong>Zip_code:</strong>
  <%= @user.zip_code %>
</p>
<p>
  <strong>School:</strong>
  <%= @user.school %>
</p>
<p>
  <strong>Years of Practice:</strong>
  <%= @user.years_practice %>
</p>
<%= link_to 'Back', users_path %>

app/views/welcome/about.html.erb
<% provide(:title, 'About Us') %>

<h1>About Us</h1>
<h1>About Uss</h1>
<h1>About Us</h1>
<h1>About Us</h1>
	

app/views/welcome/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help will be provided shortly</h1>
<h1>Help will be provided shortly1000000000000000000</h1>

app/views/welcome/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to Veterinary Practice</h1>
</div>

<h4>Below are the respective links<h4>
  <ul>
    <li>http://localhost:3000/users</li>
    <li>http://localhost:3000/users</li>
    <li>http://localhost:3000/appointments</li>
    <li>http://localhost:3000/schedules</li>
    <li>http://localhost:3000/pets</li>
  </ul>